# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resnet50.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resnet50.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eresnet50.proto\",\n\x0bReqResNet50\x12\x0b\n\x03rid\x18\x01 \x01(\t\x12\x10\n\x08\x62\x36\x34_imgs\x18\x02 \x03(\t\"*\n\x0cRespResNet50\x12\x0b\n\x03rid\x18\x01 \x01(\t\x12\r\n\x05preds\x18\x02 \x03(\x05\x32\x35\n\x08ResNet50\x12)\n\x08WhatItIs\x12\x0c.ReqResNet50\x1a\r.RespResNet50\"\x00\x62\x06proto3'
)




_REQRESNET50 = _descriptor.Descriptor(
  name='ReqResNet50',
  full_name='ReqResNet50',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='ReqResNet50.rid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b64_imgs', full_name='ReqResNet50.b64_imgs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=62,
)


_RESPRESNET50 = _descriptor.Descriptor(
  name='RespResNet50',
  full_name='RespResNet50',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='RespResNet50.rid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preds', full_name='RespResNet50.preds', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['ReqResNet50'] = _REQRESNET50
DESCRIPTOR.message_types_by_name['RespResNet50'] = _RESPRESNET50
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqResNet50 = _reflection.GeneratedProtocolMessageType('ReqResNet50', (_message.Message,), {
  'DESCRIPTOR' : _REQRESNET50,
  '__module__' : 'resnet50_pb2'
  # @@protoc_insertion_point(class_scope:ReqResNet50)
  })
_sym_db.RegisterMessage(ReqResNet50)

RespResNet50 = _reflection.GeneratedProtocolMessageType('RespResNet50', (_message.Message,), {
  'DESCRIPTOR' : _RESPRESNET50,
  '__module__' : 'resnet50_pb2'
  # @@protoc_insertion_point(class_scope:RespResNet50)
  })
_sym_db.RegisterMessage(RespResNet50)



_RESNET50 = _descriptor.ServiceDescriptor(
  name='ResNet50',
  full_name='ResNet50',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=108,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='WhatItIs',
    full_name='ResNet50.WhatItIs',
    index=0,
    containing_service=None,
    input_type=_REQRESNET50,
    output_type=_RESPRESNET50,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESNET50)

DESCRIPTOR.services_by_name['ResNet50'] = _RESNET50

# @@protoc_insertion_point(module_scope)
