# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import resnet50_pb2 as resnet50__pb2


class ResNet50Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WhatItIs = channel.unary_unary(
                '/ResNet50/WhatItIs',
                request_serializer=resnet50__pb2.ReqResNet50.SerializeToString,
                response_deserializer=resnet50__pb2.RespResNet50.FromString,
                )


class ResNet50Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def WhatItIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResNet50Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WhatItIs': grpc.unary_unary_rpc_method_handler(
                    servicer.WhatItIs,
                    request_deserializer=resnet50__pb2.ReqResNet50.FromString,
                    response_serializer=resnet50__pb2.RespResNet50.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ResNet50', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResNet50(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WhatItIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResNet50/WhatItIs',
            resnet50__pb2.ReqResNet50.SerializeToString,
            resnet50__pb2.RespResNet50.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
